### PR TITLE
fix: hide remove role button for users without permissions

### LINKED ISSUE #141: Hide delete button according to team management permissions
As a user that doesn't have the relevant manage_team permission, I shouldn't see the delete action, we should use the hook that checks for permissions for that

Image

### PR DESCRIPTION
**Pull request by jacobo-dominguez-wgu**
## Description
Adding permission check for team management `manage_library_team` or `manage_course_team` to disable or enable delete role button.

Also added query invalidation for user with all the query settings when a role is removed.

### **UPDATE:**
- Added missing tooltip for displaying a message on the delete button for own admin roles.
- Fixing bug on delete button disabled when removing filters, returning to previous table page or after getting back from role assignation wizard.

It closes https://github.com/openedx/frontend-app-admin-console/issues/141

image

#### Test 1
1. Login with a user with admin role over a resource (course or library, example Library Admin for lib:myOrg:myLib) 
2. Go to http://apps.local.openedx.io:2025/admin-console/authz
3. On the team members list, select a team member with any role assigned on the same resource your current user (Example a user with any role assigned for lib:myOrg:myLib)
4. Click on the Eye icon button to go to the audit user page for that team member.
5. On the audit page, the row for the role assigned on the same resource should display the delete role button as enabled.

#### Test 2
1. Login with a user without admin role assigned.
2. Go to http://apps.local.openedx.io:2025/admin-console/authz
3. On the team members list, select a team member and go to the audit page user by clicking the Eye icon button on the actions column.
4. On the audit page, all the delete role buttons should be disabled.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jacobo-dominguez-wgu!


This repository is currently maintained by `@openedx/committers-frontend`.


Once you've gone through the following steps feel free to tag them in a comment and let them know that your changes are ready for engineering review.

<details><summary>:radio_button: Get product approval</summary>

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.
</details>

<details><summary>:radio_button: Provide context</summary>

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads
</details>





<details><summary>:radio_button: Get a green build</summary>

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.
</details><details>


---

<details><summary>Where can I find more information?</summary>

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)
</details>

<details><summary>When can I expect my changes to be merged?</summary>

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*
</details>

File: src/authz-module/components/TableCells.tsx [hunk 1]
```diff
@@ -162,7 +165,13 @@ const ViewAllPermissionsCell = ({ row }: CellProps) => {
...
 const ActionsCell = ({ row, onClickDeleteButton, isUserAuthenticatedPage }: ActionsCellProps) => {
   const { formatMessage } = useIntl();
-  const { role } = row.original;
+  const { role, scope } = row.original;
+  const action = role.startsWith('lib') ? CONTENT_LIBRARY_PERMISSIONS.MANAGE_LIBRARY_TEAM : CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_TEAM;
+  const permission = {
+    action,
+    scope,
+  };
+  const { data: hasPermission, isLoading } = useValidateUserPermissions([permission]);
```
Comment (rodmgwgu) [inline src/authz-module/components/TableCells.tsx]: This works, but doing it item-by-item is not very efficient.

Do you see anyway we could do it in bulk? like using useValidateUserPermissions on a parent component that has knowledge of all the items currently displayed on the table? useValidateUserPermissions supports querying permissions in bulk, this results in a single request instead of one per item.

Comment (jacobo-dominguez-wgu) [reply src/authz-module/components/TableCells.tsx]: Sure, moved to a parent component to create a bulk request.

File: src/authz-module/audit-user/index.tsx [hunk 2]
```diff
@@ -52,6 +54,20 @@ const AuditUserPage = () => {
   } = useToastManager();
   const { mutate: revokeUserRoles, isPending: isRevokingUserRolePending } = useRevokeUserRoles();
 
+  const deletePermissions = useMemo(() => {
+    const uniqueScopes = [...new Set(userAssignments.map(assignment => assignment.scope))];
+    const permissions = uniqueScopes.map(scope => {
+      const action = scope.startsWith('lib') ? CONTENT_LIBRARY_PERMISSIONS.MANAGE_LIBRARY_TEAM : CONTENT_COURSE_PERMISSIONS.MANAGE_COURSE_TEAM;
```
Comment (rodmgwgu) [inline src/authz-module/audit-user/index.tsx]: Let's extract this into a dedicated function, so we can easily extend it when more scopes are added.

**Review by rodmgwgu — APPROVED** [review]
Tested and works great!, just added a nit comment, thanks!

**Comment by jacobo-dominguez-wgu** [comment]
> Tested and works great!, just added a nit comment, thanks!

Added the missing tooltip and fixed the issue on wrong delete button disabled when removing filters, returning to previous table page or after getting back from role assignation wizard.

@rodmgwgu Could you check again?

**Review by rodmgwgu — APPROVED** [review]
Tested and everything is working great now, thanks!
